# Uncomment the next line to define a global platform for your project
platform :tvos, '15.0'

target 'slides' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for slides
  pod 'MSAL', :path => '/Users/bsorrentino/WORKSPACES/GITHUB.me/AppleOS/microsoft-authentication-library-for-objc'

  target 'slidesTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
