//
//  Settings.swift
//  Auto-generated settings manifest file,
//  for use with SettingsKit. If you need to make changes,
//  edit the Settings.bundle and build the project.
//
//  Any manual changes to this file will be overwritten at build time.
//
//  Generated by the SettingsKit build tool on 2/29/16.
//
import SettingsKit

enum Settings: SettingsKit {
  case SearchHMargins
  case SearchHMargins1
  case SlideHMargins

  var identifier: String {
    switch self {
      case .SearchHMargins:
        return "search_h_margins"
      case .SearchHMargins1:
        return "search_h_margins_1"
      case .SlideHMargins:
        return "slide_h_margins"
    }
  }
}
